language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install: pip install -U tox tox-travis coverage coveralls

script: tox

after_success: coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidchall
  password:
    secure: "OpyMfUBnOA4/w75yQDxjdSwhLS/Nlaoy6yrGbs6Uv+7ZljT0C7nx5Q7elPQB8kb1Jml985X71UCusU3ADbbRghevnupzeWV5CfOC6VoKQpRKY0sD8+sUzzEY8Uxc7P/m9092A94FdVyXGth2yFdr6Eg8Y1FYJYVwB4Val197EQg="
  on:
    tags: true
    repo: davidchall/nrtest
    python: '2.7'
