#!/usr/bin/env python

from nrtest.testsuite import TestSuite

import logging
import os.path
from argparse import ArgumentParser

if __name__ == '__main__':
    parser = ArgumentParser(description='Numerical regression testing')

    parser.add_argument('app', metavar='app.json',
                        help='application config card')
    parser.add_argument('tests', metavar='test.json', nargs='+',
                        help='test config card')

    parser.add_argument('-q', '--quiet', help='suppress normal messages',
                        dest='LOGLEVEL', action='store_const',
                        const=logging.WARNING, default=logging.INFO)
    parser.add_argument('-v', '--verbose', help='output debug messages',
                        dest='LOGLEVEL', action='store_const',
                        const=logging.DEBUG, default=logging.INFO)

    args = parser.parse_args()

    LOGFORMAT = '%(levelname)s: %(message)s'
    logging.basicConfig(level=args.LOGLEVEL, format=LOGFORMAT)

    ts = TestSuite.read_config(args.app, args.tests)
    ts.execute()
    ts.write_manifest()
